### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by birkof**
@Olivier127 many thanks for you awesome work here! 
I've added some minor changes here:
- [x] Subscriber it's already autowired 
- [x] Remove unused property
- [x] Allowed nullable parents on Role & Permission entities

### CODE REVIEW

**Comment by birkof** [comment]
@Olivier127 can you have a look on this one? Unfortunately, bundle cannot be installed without one of these changes.

**Comment by Olivier127** [comment]
Yep, sorry. Thanks a lot !

**Comment by birkof** [comment]
@Olivier127 don't forget to make a new release with all of these changes. Maybe 0.4.1?

**Comment by Olivier127** [comment]
Yes off course, it's done

**Pull request merged**
